---
language: python
python: "2.7"

sudo: true
dist: xenial

addons:
  apt:
    packages:
    - python-pip
    - python-apt

install:
  # Install ansible
  - pip install ansible

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # otherwise asterisk install_prereq makes problems
  - sudo apt upgrade -y

script:
  # Install requirements
  - ansible-galaxy install -r tests/requirements.yml -p ../

  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run playbook
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo

  # Run playbook again to check idempotency
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo --diff | tee idempotence-test.log
  - >
    grep -q 'asterisk-docker.*changed=0.*failed=0' idempotence-test.log
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
